version: '3.7'

services:
  react:
    container_name: trellio_react
    image: bogdanz/trellio-frontend:latest
    restart: unless-stopped
    working_dir: /usr/src/app
    ports:
      - 4000:3000
    networks:
      - trellio

networks:
  trellio:
    external: true
