version: '3.7'

services:
  react:
    container_name: trellio_react
    build:
      context: .
      dockerfile: .docker/local/Dockerfile
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - 4444:3000
    networks:
      - trellio

networks:
  trellio:
    external: true
