version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - deploy
#      - lint_and_build
#      - deploy:
#          requires:
#            - lint_and_build

jobs:
  lint_and_build:
    docker:
      - image: circleci/node:14.15.1
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
  deploy:
    docker:
      - image: circleci/python:3.8.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - add_ssh_keys:
          fingerprints:
            - "92:47:fa:61:9b:de:52:d7:d1:be:5d:8d:b4:fe:b9:88"
      - run:
          name: deploy
          command: chmod +x ./deploy.sh && ./deploy.sh

